mysql:
  host: 127.0.0.1
  port: 3306
  db: dev_db
  username: root
  password: rootpassword
  log_level: dev

logger:
  level: info
  prefix: "[DEV] "
  director: log
  show-line: true
  log-in-console: true

system:
  host: "0.0.0.0"
  port: 8080
  mode: dev
