mysql:
  host: 127.0.0.1
  port: 3306
  dbname: dev_db
  username: root
  password: rootpassword
  log_level: dev

logger:
  level: info
  prefix: "[DEV] "
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: 8080
  env: dev
