mysql:
  host: 127.0.0.1
  port: 3306
  dbname: dev_db
  username: root
  password: 123456
  config: "parseTime=true&charset=utf8mb4&loc=Local"
  max_idle_conn: 10
  max_open_conn: 100
  log_level: dev  # possible values: debug, dev

logger:
  level: info
  prefix: "[DEV] "
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: 8080
  env: dev
